// Auto-generated by @decocms/blocks-cli/scripts/generate-loaders.ts
// Do not edit manually. Run `npm run generate:loaders` to update.
//
// Loader entries route through createLoaderEntry so their cache/cacheKey
// exports drive single-flight dedup (concurrent identical calls in one
// render collapse to one upstream call). Actions stay plain pass-throughs
// (never cached/deduped). Custom-wired entries should be excluded via
// --exclude and added manually in setup.ts.

import { createLoaderEntry } from "@decocms/blocks/sdk/cachedLoader";

export const siteLoaders: Record<string, (props: any, request?: Request) => Promise<any>> = {
  "site/actions/address/submit": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/address/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/address/submit.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/address/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/newsletter/subscribe": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/newsletter/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/newsletter/subscribe.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/newsletter/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/notifyMe/subscribe": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/notifyMe/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/notifyMe/subscribe.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/notifyMe/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/shipping/simulate": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/shipping/simulate");
    return (mod.default as any)(props, request);
  },
  "site/actions/shipping/simulate.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/shipping/simulate");
    return (mod.default as any)(props, request);
  },
  "site/actions/wishlist/submit": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/wishlist/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/wishlist/submit.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/wishlist/submit");
    return (mod.default as any)(props, request);
  },
  "site/loaders/address": createLoaderEntry("site/loaders/address", () => import("../src/loaders/address")),
  "site/loaders/address.ts": createLoaderEntry("site/loaders/address", () => import("../src/loaders/address")),
  "site/loaders/productByHandle": createLoaderEntry("site/loaders/productByHandle", () => import("../src/loaders/productByHandle")),
  "site/loaders/productByHandle.ts": createLoaderEntry("site/loaders/productByHandle", () => import("../src/loaders/productByHandle")),
  "site/loaders/searchSuggestions": createLoaderEntry("site/loaders/searchSuggestions", () => import("../src/loaders/searchSuggestions")),
  "site/loaders/searchSuggestions.ts": createLoaderEntry("site/loaders/searchSuggestions", () => import("../src/loaders/searchSuggestions")),
  "site/loaders/user": createLoaderEntry("site/loaders/user", () => import("../src/loaders/user")),
  "site/loaders/user.ts": createLoaderEntry("site/loaders/user", () => import("../src/loaders/user")),
  "site/loaders/wishlist": createLoaderEntry("site/loaders/wishlist", () => import("../src/loaders/wishlist")),
  "site/loaders/wishlist.ts": createLoaderEntry("site/loaders/wishlist", () => import("../src/loaders/wishlist")),
};
